imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: plaintext

    providers:
        in_memory:
            memory:
                users:
                    user1:
                        password: user1
                        roles: 'ROLE_USER'
                    user2:
                        password: user2
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        main:
            provider: in_memory
            form_login:
                login_path: login
                check_path: login_check
