# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    pam_authenticator:
        class: AppBundle\Security\PamAuthenticator
        arguments: ["%root_users%"]

    posix_user_provider:
        class: AppBundle\Security\User\PosixUserProvider

    app.repository.log:
        class: AppBundle\Entity\LogRepository
        factory: ["@doctrine", getRepository]
        arguments: [AppBundle\Entity\Log]
        calls:
             - [setRootUsers, ["%root_users%"]]
             - [setTokenStorage, ["@security.token_storage"]]

    app.form.type.log_search:
        class: AppBundle\Form\Type\LogSearchType
        arguments: ["@app.repository.log", "@security.token_storage", "%root_users%"]
        tags:
            - { name: form.type, alias: log_search_type }
