<?php

namespace AppBundle\Entity;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $filePath
     * @return int
     */
    public function getLastStamp($filePath)
    {
        $lastLog = $this->findOneBy(['filePath' => $filePath], ['stamp' => 'DESC']);

        return $lastLog ? $lastLog->getStamp() : 0;
    }
}
