<?php

namespace AppBundle\Entity;

use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage;

/**
 * LogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @var array
     */
    protected $rootUsers;

    /**
     * @var TokenStorage
     */
    protected $tokenStorage;

    /**
     * @param string $filePath
     * @return int
     */
    public function getLastStamp($filePath)
    {
        $lastLog = $this->findOneBy(['filePath' => $filePath], ['stamp' => 'DESC']);

        return $lastLog ? $lastLog->getStamp() : 0;
    }

    public function getLogsQuery()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $query = $qb->select('l')
    /**
     * @param array $rootUsers
     */
    public function setRootUsers(array $rootUsers)
    {
        $this->rootUsers = $rootUsers;
    }

    /**
     * @param TokenStorage $tokenStorage
     */
    public function setTokenStorage(TokenStorage $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }
            ->from($this->_entityName, 'l')
            ->getQuery()
        ;

        return $query;
    }
}
